version: '3.8'
services:
  myweb:
    environment:
    - PYTHONUNBUFFERED=1
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    depends_on:
    - myredis
  myredis:
    image: redis:6.0.5-alpine
